# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: mehrggit.azure-triggered-pipeline # Name of the pipeline resource.
    source: mehrggit.pipecontainer2 # The name of the pipeline referenced by this pipeline resource.
    trigger:    
      stages:         # This stage filter is used when evaluating conditions for 
      - RunInContainerStage # triggering your pipeline. On successful completion of all the stages

pool:
  vmImage: ubuntu-latest

stages:
- stage: triggered_pipeline_stage
  jobs:
  - job: triggered_pipeline_job
    steps:
    - script: echo was triggered
    - script: echo should not run
    - script: env | grep -i reason
